[project]
name="ftk"
version="0.1.0"
authors=[{name="Afonso", email="silva.af36@gmail.com"}]
dependencies=["jjcli"]
description=""" """
license={text=""}

[project.scripts]
ftk-occ="ftk.base:main"
ftk-cnt="ftk.count:main"
